{% set name = "dagster_aws" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: 0bfb56df1ddcc180f3dc38a2c57da6826090ff176bf484ba32d817c67602acc8

build:
  number: 0
  noarch: python
  entry_points:
    - dagster-aws = dagster_aws.cli.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - boto3 1.9.*
    - dagster {{ version }}.*
    - python
    - requests
    - terminaltables

test:
  imports:
    - dagster_aws
    - dagster_aws.cli
    - dagster_aws.cloudwatch
    - dagster_aws.emr
    - dagster_aws.s3
  commands:
    - dagster-aws --help

about:
  home: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-aws
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: Package for AWS-specific Dagster framework solid and resource components.

extra:
  recipe-maintainers:
    - conda-forge/dagster
